# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-26 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='userId',
            field=models.CharField(default='', max_length=50, verbose_name='账号'),
        ),
    ]
