# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-11 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0002_usermessage_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='loginFlag',
            field=models.IntegerField(default=0, verbose_name='登陆状态'),
            preserve_default=False,
        ),
    ]
