# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-26 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50, verbose_name='用户名')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('date', models.DateField(verbose_name='注册日期')),
                ('isVerified', models.IntegerField(verbose_name='激活状态')),
                ('remainder', models.IntegerField(verbose_name='剩余天数')),
            ],
            options={
                'verbose_name': '用户信息',
            },
        ),
    ]
